security_login:
    path: /login
    controller: App\Controller\SecurityController::login

security_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

user_registration:
    path: /register
    controller: App\Controller\RegistrationController::registerAction

search_file:
    path: /search
    controller: App\Controller\SearchController::search

displayResearch:
    path: /displayResearch
    controller : App\Controller\SearchController::displayResearch

home:
    path: /home
    controller: App\Controller\DefaultController::home

stats:
    path: /admin/stats
    controller: App\Controller\DocController::stats

account:
    path: /account
    controller: App\Controller\UserController::details

delete_file:
    path: /deleteFile
    controller: App\Controller\DocController::deleteDocument

doc_details:
    path: /doc/details/{id}
    controller: App\Controller\DocController::getDocumentDetails

doc_show:
    path: /doc/view/{id}
    controller: App\Controller\DocController::showDocument

doc_delete:
    path: /doc/delete/{id}
    controller: App\Controller\DocController::deleteDocument

folder_delete:
    path: /folder/delete/{id}
    controller: App\Controller\DocController::deleteFolder

create_type:
    path: /type
    controller: App\Controller\TypeController::createType

doc_create:
    path: /doc/create
    controller: App\Controller\DocController::createDocument

folder_create:
    path: /folder/create
    controller: App\Controller\DocController::createFolder


