index:
    path: /
    controller: App\Controller\DefaultController::index

security_login:
    path: /login
    controller: App\Controller\SecurityController::login

security_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

user_registration:
    path: /register
    controller: App\Controller\RegistrationController::registerAction

search_file:
    path: /search
    controller: App\Controller\SearchController::search

displayResearch:
    path: /displayResearch
    controller : App\Controller\SearchController::displayResearch

home:
    path: /GED/home
    controller: App\Controller\DefaultController::home

stats:
    path: /GED/stats
    controller: App\Controller\DocController::stats

account:
    path: /GED/account
    controller: App\Controller\UserController::details

delete_file:
    path: /deleteFile
    controller: App\Controller\DocController::deleteDocument
